name: smgi_teacher
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
                              # All firebase related Depandences
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.5
  firebase_messaging: ^14.7.15
  flutter_local_notifications: ^19.2.1
  file_picker: ^8.0.7 
  url_launcher: ^6.3.1
  open_file: ^3.5.4
  # flutter_local_notifications: ^16.3.2
                              # VideoSplash related dependences 
  video_player: ^2.8.2
                              # Getx 
  get: ^4.6.6
                              # other depandeceshttp: http: 
  awesome_snackbar_content: ^0.1.1
  email_validator: ^2.1.17
  font_awesome_flutter: ^10.6.0
  liquid_pull_to_refresh: ^3.0.1
  animated_text_kit: ^4.2.2
  image_picker: ^1.0.7
  uuid: ^4.3.3
  # emoji_picker_flutter: ^2.0.0




            
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/
    - assets/videos/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Encode 
      fonts:
      # assets\fonts\Encode_Sans_Expanded
          - asset: assets\fonts\Encode_Sans_Expanded\EncodeSansExpanded-Medium.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
